# Inserts a blank line between shell prompts
add_newline = false
continuation_prompt = "â–¶â–¶"

format = """\
  $cmd_duration\
  $shell\
  $status\
  $sudo\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $rust\
  $character\
"""

# Replace the "â¯" symbol in the prompt with "âœ"
[character] 
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ—](bold red) "

[cmd_duration]
min_time = 5_000

[directory]
truncation_length = 4
truncation_symbol = "â€¦/"
home_symbol="ï€• "
repo_root_style="blue underline"
style="blue"

# One one Line
[line_break]
disabled = true

[dotnet]
disabled = true

[status]
disabled = false

[sudo]
disabled = false

[shell]
disabled = false
bash_indicator = "î• "
zsh_indicator = "ğŸš€ "
format="[$indicator](bold green)"


